# Generated by Django 4.1.5 on 2023-02-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=255)),
                ('description', models.CharField(help_text='Описание', max_length=255)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ФИО', max_length=255)),
                ('email', models.EmailField(help_text='e-mail', max_length=254)),
                ('role', models.CharField(choices=[(1, 'Начальник'), (2, 'Исполнитель')], help_text='Роль пользователя', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название задачи', max_length=255)),
                ('task', models.TextField(help_text='Описание задачи')),
                ('creator', models.CharField(help_text='ФИО создателя задачи', max_length=255)),
                ('status', models.CharField(choices=[(0, 'Не назначено'), (1, 'Назначено'), (2, 'В работе'), (3, 'Подтверждение выполнения'), (4, 'Вернулось в работу'), (5, 'Выполнено'), (6, 'Отменено')], help_text='Статус задачи', max_length=255)),
                ('change_history', models.TextField(help_text='История изменения статусов')),
                ('assignee', models.ForeignKey(blank=True, help_text='ИД Исполнителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jira.users')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Sprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(help_text='Дата начала спринта')),
                ('date_end', models.DateField(help_text='Дата окончания спринта')),
                ('project_id', models.ForeignKey(help_text='ИД Проекта', on_delete=django.db.models.deletion.CASCADE, to='jira.projects')),
            ],
            options={
                'verbose_name': 'Спринт',
                'verbose_name_plural': 'Спринты',
            },
        ),
    ]
