# Generated by Django 4.1.5 on 2023-03-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jira", "0003_remove_users_name_alter_users_dept_alter_users_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="dept",
            field=models.CharField(
                choices=[
                    ("1", "Ордапобедит"),
                    ("2", "Нужнопостроитьзиккурат"),
                    ("3", "Очемшумятдеревья"),
                ],
                help_text="Отдел",
                max_length=255,
                verbose_name="Отдел",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("1", "Начальник"), ("2", "Исполнитель")],
                help_text="Роль пользователя",
                max_length=255,
                verbose_name="Роль",
            ),
        ),
    ]
