# Generated by Django 4.1.5 on 2023-03-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jira", "0004_alter_users_dept_alter_users_role"),
    ]

    operations = [
        migrations.RemoveField(model_name="tasks", name="change_history",),
        migrations.AddField(
            model_name="tasks",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Спринт, когда нужно сделать",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jira.sprints",
            ),
        ),
    ]
