# Generated by Django 4.1.5 on 2023-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jira", "0005_remove_tasks_change_history_tasks_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="change_history",
            field=models.TextField(
                blank=True, help_text="История изменения задачи", null=True
            ),
        ),
    ]
