# Generated by Django 4.1.5 on 2023-03-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jira", "0006_tasks_change_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="creator",
            field=models.CharField(help_text="ИД Создателя", max_length=255),
        ),
    ]
