# Generated by Django 4.1.5 on 2023-03-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jira", "0008_sprints_dept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprints",
            name="dept",
            field=models.CharField(
                default="1", help_text="Отдел", max_length=255, verbose_name="Отдел"
            ),
        ),
    ]
